import express from "express";
import {
  createPayment,
  updatePaymentStatus,
  getAllPayments,
  getPaymentByOrder,
} from "../controllers/paymentController.js";

import authMiddleware from "../middlewares/authMiddleware.js";
import { allowRoles } from "../middlewares/roleMiddleware.js";
import { validate } from "../middlewares/validateMiddleware.js";
import {
  createPaymentSchema,
  updatePaymentStatusSchema,
} from "../validations/paymentValidation.js";

const router = express.Router();

/**
 * @swagger
 * tags:
 *   name: Payments
 *   description: Payment management APIs
 */

/**
 * @swagger
 * /api/payments:
 *   post:
 *     summary: Create payment for an order
 *     description: Creates a payment record for an existing order. This route is available for admins and laundry owners.
 *     tags:
 *       - Payments
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - orderId
 *               - method
 *               - amount
 *             properties:
 *               orderId:
 *                 type: integer
 *                 example: 1
 *               method:
 *                 type: string
 *                 enum:
 *                   - CASH
 *                   - CARD
 *                   - ONLINE
 *                 example: CASH
 *               amount:
 *                 type: number
 *                 example: 1100
 *               status:
 *                 type: string
 *                 enum:
 *                   - PENDING
 *                   - PAID
 *                   - FAILED
 *                   - REFUNDED
 *                 example: PENDING
 *     responses:
 *       201:
 *         description: Payment recorded successfully
 *       400:
 *         description: Validation failed, order not found, or payment already exists
 *       401:
 *         description: Unauthorized
 *       403:
 *         description: Forbidden
 *       500:
 *         description: Server error
 */
router.post(
  "/",
  authMiddleware,
  allowRoles("ADMIN", "LAUNDRY_OWNER"),
  validate(createPaymentSchema),
  createPayment
);

/**
 * @swagger
 * /api/payments/{id}/status:
 *   patch:
 *     summary: Update payment status
 *     description: Updates the status of an existing payment. When a payment becomes PAID, commission records can be generated by the backend.
 *     tags:
 *       - Payments
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: Payment ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - status
 *             properties:
 *               status:
 *                 type: string
 *                 enum:
 *                   - PENDING
 *                   - PAID
 *                   - FAILED
 *                   - REFUNDED
 *                 example: PAID
 *     responses:
 *       200:
 *         description: Payment status updated successfully
 *       400:
 *         description: Validation failed or invalid payment status
 *       401:
 *         description: Unauthorized
 *       403:
 *         description: Forbidden
 *       404:
 *         description: Payment not found
 *       500:
 *         description: Server error
 */
router.patch(
  "/:id/status",
  authMiddleware,
  allowRoles("ADMIN", "LAUNDRY_OWNER"),
  validate(updatePaymentStatusSchema),
  updatePaymentStatus
);

/**
 * @swagger
 * /api/payments/admin/all:
 *   get:
 *     summary: Get all payments
 *     description: Admin-only endpoint for viewing all platform payment records.
 *     tags:
 *       - Payments
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: Payments fetched successfully
 *       401:
 *         description: Unauthorized
 *       403:
 *         description: Forbidden
 *       500:
 *         description: Server error
 */
router.get(
  "/admin/all",
  authMiddleware,
  allowRoles("ADMIN"),
  getAllPayments
);

/**
 * @swagger
 * /api/payments/order/{orderId}:
 *   get:
 *     summary: Get payment by order ID
 *     description: Retrieves payment information linked to a specific order.
 *     tags:
 *       - Payments
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: orderId
 *         required: true
 *         schema:
 *           type: integer
 *         description: Order ID
 *     responses:
 *       200:
 *         description: Payment fetched successfully
 *       401:
 *         description: Unauthorized
 *       403:
 *         description: Forbidden
 *       404:
 *         description: Payment not found for this order
 *       500:
 *         description: Server error
 */
router.get(
  "/order/:orderId",
  authMiddleware,
  allowRoles("ADMIN", "LAUNDRY_OWNER", "CUSTOMER"),
  getPaymentByOrder
);

export default router;